[tool.poetry]
name = "ytbryan-fair"
version = "0.1.0"
description = ""
authors = ["ytbryan <ytbryan@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.12.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
